# Generated by Django 5.1.4 on 2025-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="picture",
        ),
        migrations.AddField(
            model_name="item",
            name="supplier",
            field=models.CharField(default=1, max_length=20, verbose_name="Поставщик"),
            preserve_default=False,
        ),
    ]
