# Generated by Django 5.1.4 on 2025-01-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_useritemconnection"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useritemconnection",
            options={
                "ordering": ["pk"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Пользователь-Продукт",
            },
        ),
        migrations.CreateModel(
            name="OrganisationItemConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("amount", models.IntegerField(verbose_name="Количество")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.item",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisation",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Организация-Продукт",
                "ordering": ["pk"],
            },
        ),
    ]
