# Generated by Django 5.1.4 on 2025-01-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="picture",
        ),
    ]
