# Generated by Django 5.1.4 on 2025-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_remove_item_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("IU", "В использовании"),
                    ("OK", "Доступен для аренды"),
                    ("BR", "Сломан"),
                ],
                default="OK",
                max_length=2,
                verbose_name="Статус инвентаря",
            ),
        ),
    ]
