# Generated by Django 5.1.4 on 2025-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_item_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="status",
        ),
        migrations.AddField(
            model_name="item",
            name="picture",
            field=models.ImageField(default=1, upload_to="static/items", verbose_name="Картинка"),
            preserve_default=False,
        ),
    ]
