# Generated by Django 5.1.4 on 2025-01-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Пользователь с такой почтой уже зарегистрировался"},
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("PT", "Участник"), ("TC", "Руководитель"), ("SP", "Поставщик")],
                default="PT",
                max_length=2,
                verbose_name="user status",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="surname",
            field=models.CharField(blank=True, max_length=150, verbose_name="surname"),
        ),
    ]
