# Generated by Django 5.1.4 on 2025-01-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_bio_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("PT", "Участник"), ("TC", "Руководитель")],
                default="PT",
                max_length=2,
                verbose_name="user status",
            ),
        ),
    ]
